name: Multiverse-NetherPortals
main: com.onarandombox.MultiverseNetherPortals.MultiverseNetherPortals
authors: ['Rigby', 'fernferret']
version: maven-version-number
depend: ['Multiverse-Core']
commands:
  mvnp:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpl:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpu:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnps:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnplink:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpunlink:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpshow:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>