name: Multiverse-NetherPortals
main: com.onarandombox.MultiverseNetherPortals.MultiverseNetherPortals
authors: ['Rigby', 'fernferret']
version: 2.0
commands:
  mvnp:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpl:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpu:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnps:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>